[package]
name = "substudy-backend"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
env_logger = "0.4"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.1"
structopt-derive = "0.1"
substudy = { path = ".." }
url = "1.6"

